/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_Admin;
import Controlador.Controlador_Login;
import java.awt.Color;



import javax.swing.JOptionPane;

public class Admin extends javax.swing.JFrame {
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();

        this.setLocationRelativeTo(null);
       
    }

    void exit() {
        JOptionPane.showMessageDialog(this, "Hasta luego :D");
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Left_Panel = new javax.swing.JPanel();
        Icon_sena = new javax.swing.JLabel();
        Estudiantes = new javax.swing.JButton();
        Profesores = new javax.swing.JButton();
        Cursos = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Panel_right = new javax.swing.JPanel();
        Background_image = new javax.swing.JLabel();
        Lbl_Edusena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(1366, 768));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Left_Panel.setBackground(new java.awt.Color(0, 173, 0));
        Left_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon_sena.setBackground(new java.awt.Color(0, 173, 0));
        Icon_sena.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Icon_sena.setForeground(new java.awt.Color(255, 255, 255));
        Icon_sena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon_sena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_sin_fondo-removebg-preview.png"))); // NOI18N
        Icon_sena.setText("EDUSENA");
        Icon_sena.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Icon_sena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Icon_sena.setIconTextGap(30);
        Icon_sena.setOpaque(true);
        Icon_sena.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Icon_sena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icon_senaMouseClicked(evt);
            }
        });
        Left_Panel.add(Icon_sena, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 183));

        Estudiantes.setBackground(new java.awt.Color(255, 255, 255));
        Estudiantes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Estudiantes.setForeground(new java.awt.Color(0, 173, 0));
        Estudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/e.png"))); // NOI18N
        Estudiantes.setText("Estudiantes");
        Estudiantes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        Estudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Estudiantes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Estudiantes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Estudiantes.setIconTextGap(27);
        Estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EstudiantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EstudiantesMouseExited(evt);
            }
        });
        Estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudiantesActionPerformed(evt);
            }
        });
        Left_Panel.add(Estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 70));

        Profesores.setBackground(new java.awt.Color(255, 255, 255));
        Profesores.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Profesores.setForeground(new java.awt.Color(0, 173, 0));
        Profesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profesor.png"))); // NOI18N
        Profesores.setText("Profesores");
        Profesores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        Profesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profesores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Profesores.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Profesores.setIconTextGap(30);
        Left_Panel.add(Profesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 250, 70));

        Cursos.setBackground(new java.awt.Color(255, 255, 255));
        Cursos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Cursos.setForeground(new java.awt.Color(0, 173, 0));
        Cursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cursos.png"))); // NOI18N
        Cursos.setText("Cursos");
        Cursos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        Cursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cursos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cursos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Cursos.setIconTextGap(58);
        Left_Panel.add(Cursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 250, 70));

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(0, 173, 0));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        Exit.setText("Salir");
        Exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Exit.setIconTextGap(73);
        Left_Panel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 250, 70));

        Background.add(Left_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 768));

        Panel_right.setBackground(new java.awt.Color(255, 255, 255));
        Panel_right.setPreferredSize(new java.awt.Dimension(1360, 770));

        Background_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N

        Lbl_Edusena.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Lbl_Edusena.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Edusena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Edusena.setText("EDUSENA");

        javax.swing.GroupLayout Panel_rightLayout = new javax.swing.GroupLayout(Panel_right);
        Panel_right.setLayout(Panel_rightLayout);
        Panel_rightLayout.setHorizontalGroup(
            Panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_rightLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addGroup(Panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Background_image, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Edusena, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        Panel_rightLayout.setVerticalGroup(
            Panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_rightLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(Background_image, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_Edusena, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );

        Background.add(Panel_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 0, 1360, 770));

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Icon_senaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icon_senaMouseClicked

    }//GEN-LAST:event_Icon_senaMouseClicked

    private void EstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudiantesActionPerformed

        //c.show_e();
        //c.show_table();
// TODO add your handling code here:*/
    }//GEN-LAST:event_EstudiantesActionPerformed

    private void EstudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstudiantesMouseEntered
        Estudiantes.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_EstudiantesMouseEntered

    private void EstudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstudiantesMouseExited
        Estudiantes.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_EstudiantesMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    
        //Students es = new Students();
      
       // Admin admin = new Admin();
        //Controlador_Admin c = new Controlador_Admin(admin, es);
        //admin.setVisible(true);
     
        /*Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Background_image;
    public javax.swing.JButton Cursos;
    public javax.swing.JButton Estudiantes;
    public javax.swing.JButton Exit;
    private javax.swing.JLabel Icon_sena;
    private javax.swing.JLabel Lbl_Edusena;
    public javax.swing.JPanel Left_Panel;
    public javax.swing.JPanel Panel_right;
    public javax.swing.JButton Profesores;
    // End of variables declaration//GEN-END:variables
}
