/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author ADSI
 */
public class Estudiante_log extends javax.swing.JFrame {

    /**
     * Creates new form Estudiante_log
     */
    public Estudiante_log() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Left_Panel = new javax.swing.JPanel();
        Icon_sena = new javax.swing.JLabel();
        perfil = new javax.swing.JButton();
        Actividades = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Panel_right = new javax.swing.JPanel();
        Background_image = new javax.swing.JLabel();
        Lbl_Edusena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(1366, 768));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Left_Panel.setBackground(new java.awt.Color(0, 173, 0));
        Left_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon_sena.setBackground(new java.awt.Color(0, 173, 0));
        Icon_sena.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Icon_sena.setForeground(new java.awt.Color(255, 255, 255));
        Icon_sena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon_sena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_sin_fondo-removebg-preview.png"))); // NOI18N
        Icon_sena.setText("EDUSENA");
        Icon_sena.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Icon_sena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Icon_sena.setIconTextGap(30);
        Icon_sena.setOpaque(true);
        Icon_sena.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Icon_sena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icon_senaMouseClicked(evt);
            }
        });
        Left_Panel.add(Icon_sena, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 183));

        perfil.setBackground(new java.awt.Color(255, 255, 255));
        perfil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        perfil.setForeground(new java.awt.Color(0, 173, 0));
        perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/e.png"))); // NOI18N
        perfil.setText("Perfil");
        perfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        perfil.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        perfil.setIconTextGap(60);
        perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perfilMouseExited(evt);
            }
        });
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });
        Left_Panel.add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 250, 70));

        Actividades.setBackground(new java.awt.Color(255, 255, 255));
        Actividades.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Actividades.setForeground(new java.awt.Color(0, 173, 0));
        Actividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/actividad.png"))); // NOI18N
        Actividades.setText("Actividades");
        Actividades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        Actividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Actividades.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Actividades.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Actividades.setIconTextGap(10);
        Left_Panel.add(Actividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 70));

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(0, 173, 0));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        Exit.setText("Salir");
        Exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Exit.setIconTextGap(65);
        Left_Panel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 250, 70));

        Background.add(Left_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 770));

        Panel_right.setBackground(new java.awt.Color(255, 255, 255));
        Panel_right.setPreferredSize(new java.awt.Dimension(1360, 770));

        Background_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N

        Lbl_Edusena.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Lbl_Edusena.setForeground(new java.awt.Color(0, 173, 0));
        Lbl_Edusena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Edusena.setText("EDUSENA");

        javax.swing.GroupLayout Panel_rightLayout = new javax.swing.GroupLayout(Panel_right);
        Panel_right.setLayout(Panel_rightLayout);
        Panel_rightLayout.setHorizontalGroup(
            Panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_rightLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addGroup(Panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Background_image, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Edusena, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        Panel_rightLayout.setVerticalGroup(
            Panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_rightLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(Background_image, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_Edusena, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );

        Background.add(Panel_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 0, 1360, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Icon_senaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icon_senaMouseClicked

    }//GEN-LAST:event_Icon_senaMouseClicked

    private void perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseEntered
        perfil.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_perfilMouseEntered

    private void perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseExited
        perfil.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_perfilMouseExited

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed

        //c.show_e();
        //c.show_table();
        // TODO add your handling code here:*/
    }//GEN-LAST:event_perfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudiante_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudiante_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudiante_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudiante_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estudiante_log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Actividades;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Background_image;
    public javax.swing.JButton Exit;
    private javax.swing.JLabel Icon_sena;
    private javax.swing.JLabel Lbl_Edusena;
    public javax.swing.JPanel Left_Panel;
    public javax.swing.JPanel Panel_right;
    public javax.swing.JButton perfil;
    // End of variables declaration//GEN-END:variables
}
