-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 20:48:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colegio` DEFAULT CHARACTER SET utf8 ;
USE `colegio` ;

-- -----------------------------------------------------
-- Table `colegio`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`Roles` (
  `id_Rol` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_Rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`Cursos` (
  `id_Cursos` VARCHAR(3) NOT NULL,
  `Grado` INT NOT NULL,
  `Seccion` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_Cursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`estudiantes` (
  `id_Estudiantes` INT NOT NULL,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` BIGINT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Grado` INT NOT NULL,
  `Seccion` CHAR(1) NOT NULL,
  `id_Curso` VARCHAR(5) NOT NULL,
  `Contraseña` VARCHAR(20) NOT NULL,
  `Rol` VARCHAR(10) NOT NULL DEFAULT 'student',
  PRIMARY KEY (`id_Estudiantes`),
  INDEX `Rol_idx` (`Rol` ASC) VISIBLE,
  INDEX `id_Curso_idx` (`id_Curso` ASC) VISIBLE,
  CONSTRAINT `Rol`
    FOREIGN KEY (`Rol`)
    REFERENCES `colegio`.`Roles` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Curso`
    FOREIGN KEY (`id_Curso`)
    REFERENCES `colegio`.`Cursos` (`id_Cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`Profesores` (
  `id_Profesor` INT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefono` BIGINT NOT NULL,
  `Rol` VARCHAR(10) NOT NULL DEFAULT 'teacher',
  PRIMARY KEY (`id_Profesor`),
  INDEX `Rol_idx` (`Rol` ASC) VISIBLE,
  CONSTRAINT `Rol`
    FOREIGN KEY (`Rol`)
    REFERENCES `colegio`.`Roles` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`Asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`Asignaturas` (
  `id_Asignatura` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Asignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`Notas` (
  `id_Notas` INT NOT NULL AUTO_INCREMENT,
  `id_Alumno` INT NOT NULL,
  `id_Profesor` INT NOT NULL,
  `id_Asignatura` INT NOT NULL,
  `id_Curso` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_Notas`),
  INDEX `id_Alumno_idx` (`id_Alumno` ASC) VISIBLE,
  INDEX `id_Profesor_idx` (`id_Profesor` ASC) VISIBLE,
  INDEX `id_Asignatura_idx` (`id_Asignatura` ASC) VISIBLE,
  INDEX `id_Curso_idx` (`id_Curso` ASC) VISIBLE,
  CONSTRAINT `id_Alumno`
    FOREIGN KEY (`id_Alumno`)
    REFERENCES `colegio`.`estudiantes` (`id_Estudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Profesor`
    FOREIGN KEY (`id_Profesor`)
    REFERENCES `colegio`.`Profesores` (`id_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Asignatura`
    FOREIGN KEY (`id_Asignatura`)
    REFERENCES `colegio`.`Asignaturas` (`id_Asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Curso`
    FOREIGN KEY (`id_Curso`)
    REFERENCES `colegio`.`Cursos` (`id_Cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`Admin` (
  `id_Admin` INT NOT NULL,
  `Rol` VARCHAR(10) NOT NULL DEFAULT 'admin',
  PRIMARY KEY (`id_Admin`),
  INDEX `Rol_idx` (`Rol` ASC) VISIBLE,
  CONSTRAINT `Rol`
    FOREIGN KEY (`Rol`)
    REFERENCES `colegio`.`Roles` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
